#Santiago Vázquez García
version: '3.3'

services:
  web:
    image: odoo:17
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./volumesOdoo/addons:/mnt/extra-addons
      - ./volumesOdoo/odoo/filestore_SVG:/var/lib/odoo/filestore
      - ./volumesOdoo/odoo/sessions_SVG:/var/lib/odoo/sessions
      - ./volumesOdoo/config_odoo:/etc/odoo
      - ./volumesOdoo/log:/var/log/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    command: --dev=all 

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - ./volumesOdoo/dataPostgreSQL:/var/lib/postgresql/data
